---
name: base-site-config
---
Axllent\CMSTweaks\MetadataTab:
  use_tab: true
  tab_title: 'SEO'
  tab_to_right: true
  page_name_title: 'Page Title'
  move_title_to_advanced: false

SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - Dynamic\Base\Extension\CompanyDataExtension
    - Dynamic\Base\Extension\IntegrationsDataExtension
    - Dynamic\Base\Extension\TemplateDataExtension

SilverStripe\CMS\Model\SiteTree:
  extensions:
    - Dynamic\Base\Extension\CmsDesignDataExtension

Page:
  extensions:
    - Vulcan\Seo\Extensions\PageHealthExtension
    - Vulcan\Seo\Extensions\PageSeoExtension
    - Dynamic\Base\Extension\SeoExtension

Dynamic\Base\Page\HomePage:
  extensions:
    - Dynamic\CoreTools\ORM\HeaderImageDataExtension
    - DNADesign\Elemental\Extensions\ElementalPageExtension

Dynamic\Base\Page\BlockPage:
  extensions:
    - Dynamic\CoreTools\ORM\HeaderImageDataExtension
    - DNADesign\Elemental\Extensions\ElementalPageExtension

Dynamic\Base\Page\CampaignLandingPage:
  extensions:
    - Dynamic\CoreTools\ORM\HeaderImageDataExtension
    - DNADesign\Elemental\Extensions\ElementalPageExtension

SilverStripe\Blog\Model\BlogPost:
  extensions:
    - DNADesign\Elemental\Extensions\ElementalPageExtension
    - Dynamic\CoreTools\ORM\PreviewExtension
    - Dynamic\Base\Extension\BlogPostDataExtension

Dynamic\Base\Model\CompanyAddress:
  extensions:
    - Dynamic\SilverStripeGeocoder\AddressDataExtension

SilverStripe\UserForms\Model\EditableFormField:
  extensions:
    - Dynamic\CoreTools\ORM\ContentAuthorPermissionManager

SilverStripe\UserForms\Model\EditableCustomRule:
  extensions:
    - Dynamic\CoreTools\ORM\ContentAuthorPermissionManager
