---
name: base-site-config
After:
  - '*'
---
SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - Dynamic\Base\Extension\CompanyDataExtension
    - Dynamic\Base\Extension\IntegrationsDataExtension
    - Dynamic\Base\Extension\TemplateDataExtension
    - Dynamic\SiteTools\Extension\ReviewContentDataExtension

SilverStripe\CMS\Model\SiteTree:
  extensions:
    - Dynamic\Base\Extension\CmsDesignDataExtension

Page:
  extensions:
    - QuinnInteractive\Seo\Extensions\PageHealthExtension
    - QuinnInteractive\Seo\Extensions\PageSeoExtension
    - Dynamic\Base\Extension\SeoExtension

Dynamic\Base\Page\HomePage:
  extensions:
    - Dynamic\SiteTools\Extension\HeaderImageExtension
    - DNADesign\Elemental\Extensions\ElementalPageExtension

Dynamic\Base\Page\BlockPage:
  extensions:
    - Dynamic\SiteTools\Extension\HeaderImageExtension
    - DNADesign\Elemental\Extensions\ElementalPageExtension

Dynamic\Base\Page\CampaignLandingPage:
  extensions:
    - Dynamic\SiteTools\Extension\HeaderImageExtension
    - DNADesign\Elemental\Extensions\ElementalPageExtension

SilverStripe\Blog\Model\BlogPost:
  extensions:
    - DNADesign\Elemental\Extensions\ElementalPageExtension
    - Dynamic\SiteTools\Extension\PreviewExtension
    - Dynamic\Base\Extension\BlogPostDataExtension

Dynamic\Base\Model\CompanyAddress:
  extensions:
    - Dynamic\SilverStripeGeocoder\AddressDataExtension
    - Dynamic\SiteTools\Extension\ContactDataExtension

SilverStripe\UserForms\Model\EditableFormField:
  extensions:
    - Dynamic\SiteTools\Extension\DataobjectPermissionExtension

SilverStripe\UserForms\Model\EditableCustomRule:
  extensions:
    - Dynamic\SiteTools\Extension\DataobjectPermissionExtension

Axllent\CMSTweaks\MetadataTab:
  use_tab: true
  tab_title: 'SEO'
  tab_to_right: true
  page_name_title: 'Page Title'
  move_title_to_advanced: false

Axllent\CMSTweaks\CMSTweaks:
  invalid_elements: ""
  extended_valid_elements: "img[class|src|alt|title|hspace|vspace|width|height|align|name|usemap|data*],iframe[src|name|width|height|align|frameborder|marginwidth|marginheight|scrolling],object[width|height|data|type],param[name|value],map[class|name|id],area[shape|coords|href|target|alt],video[loop|autoplay|muted|playsinline|controls],source[src|type]"

SilverStripe\View\SSViewer:
  rewrite_hash_links: false

SilverStripe\UserForms\Model\UserDefinedForm:
  block_default_userforms_js: true
  block_default_userforms_css: true

DNADesign\ElementalUserForms\Model\ElementForm:
  block_default_userforms_js: true
  block_default_userforms_css: true

DNADesign\Elemental\Controllers\ElementController:
  include_default_styles: false
