---
name: base-site-config
After:
  - '*'
---
SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - Dynamic\Base\Extension\TemplateDataExtension
    - Dynamic\SiteTools\Extension\ReviewContentDataExtension

SilverStripe\CMS\Model\SiteTree:
  extensions:
    - Dynamic\Base\Extension\CmsDesignDataExtension
    - Dynamic\Base\Extension\SeoExtension

Page:
  defaults:
    ShowSharingLinks: 1
  disallowed_elements:
    - 'Dynamic\Elements\Blog\Elements\ElementBlogOverview'
    - 'Dynamic\Elements\Blog\Elements\ElementBlogPagination'
    - 'Dynamic\Elements\Blog\Elements\ElementBlogWidgets'

Dynamic\Base\Page\HomePage:
  extensions:
    - DNADesign\Elemental\Extensions\ElementalPageExtension
    - Dynamic\Carousel\Extension\CarouselPageExtension
  elemental_keep_content_field: true

Dynamic\Base\Page\BlockPage:
  extensions:
    - DNADesign\Elemental\Extensions\ElementalPageExtension
    - Dynamic\Carousel\Extension\CarouselPageExtension
  elemental_keep_content_field: true

Dynamic\Base\Page\CampaignLandingPage:
  extensions:
    - DNADesign\Elemental\Extensions\ElementalPageExtension
    - Dynamic\Carousel\Extension\CarouselPageExtension
  elemental_keep_content_field: true

SilverStripe\Blog\Model\BlogPost:
  extensions:
    - DNADesign\Elemental\Extensions\ElementalPageExtension
    - Dynamic\SiteTools\Extension\PreviewExtension
  elemental_keep_content_field: true

SilverStripe\UserForms\Model\EditableFormField:
  extensions:
    - Dynamic\SiteTools\Extension\DataobjectPermissionExtension

SilverStripe\UserForms\Model\EditableCustomRule:
  extensions:
    - Dynamic\SiteTools\Extension\DataobjectPermissionExtension

